#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2014 Nico Isenbeck <contact@bananian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# get Bananian platform (default: BananaPi) and version
[ -f /etc/bananian_platform ] && BANANIAN_PLATFORM=$(cat /etc/bananian_platform) || BANANIAN_PLATFORM="BananaPi"
[ -f /etc/bananian_version ] && BANANIAN_VERSION=$(cat /etc/bananian_version) || BANANIAN_VERSION=140801

if [ $BANANIAN_VERSION -lt 150101 ]; then {
        echo -e "\033[0;31mThis version of bananian-hardware requires Bananian Linux 15.01 (or later). Exiting\033[0m"
        exit
} fi

# prepare tmp dir
TMPDIR=$(mktemp -d)
cd $TMPDIR

# mount /dev/mmcblk0p1
mkdir ${TMPDIR}/mnt
mount /dev/mmcblk0p1 ${TMPDIR}/mnt

# fex dir
FEXDIR="${TMPDIR}/mnt/fex"

# read available fex configurations
RADIOLIST=()
for FEX in ${FEXDIR}/*
do
	FEX=$(basename $FEX)
	if [ "$FEX" = "$BANANIAN_PLATFORM" ]; then {
		RADIOLIST+=("$FEX" "" "ON")
	} else {
		RADIOLIST+=("$FEX" "" "OFF")
	} fi
done

# show dialog
BANANIAN_PLATFORM=$(whiptail --title "Bananian hardware configuration" --radiolist \
	"\nPlease select your Banana board:" 20 78 10 \
	"${RADIOLIST[@]}" \
	3>&1 1>&2 2>&3)

if [[ $BANANIAN_PLATFORM = *"OTG"* ]] || [[ $BANANIAN_PLATFORM = *"otg"* ]]; then {
	if ! (whiptail --title "Warning" --yesno "Enabling OTG can lead to an unbootable system!\nTo avoid this issue please make sure you use the 'DC in' port for power supply\nin combination with a reliable 2 A power adapter\n\nDo you want to continue?" 12 85); then {
		BANANIAN_PLATFORM=""
	} fi
} fi

# verify selection and set correct script.bin
if [[ -z $BANANIAN_PLATFORM ]]; then {
	echo -e "\033[0;31mNo platform selected. exiting!\033[0m"
} else {
	if [[ -f ${FEXDIR}/${BANANIAN_PLATFORM}/script.bin ]]; then {
		cp ${FEXDIR}/${BANANIAN_PLATFORM}/script.bin ${TMPDIR}/mnt/script.bin
		echo $BANANIAN_PLATFORM > /etc/bananian_platform
		echo -e "Hardware configuration has been set to: ${BANANIAN_PLATFORM}. Please reboot your system!"
	} else {
		echo -e "\033[0;31mscript.bin not found. exiting!\033[0m"
	} fi
} fi

# clean up
umount ${TMPDIR}/mnt && rm -rf $TMPDIR
