#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2014 Nico Isenbeck <contact@bananian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# get Bananian platform (default: BananaPi)
[ -f /etc/bananian_platform ] && BANANIAN_PLATFORM=$(cat /etc/bananian_platform) || BANANIAN_PLATFORM="BananaPi"

# prepare tmp dir
TMPDIR=$(mktemp -d)
cd $TMPDIR

# mount /dev/mmcblk0p1
mkdir ${TMPDIR}/mnt
mount /dev/mmcblk0p1 ${TMPDIR}/mnt

# fex dir
FEXDIR="${TMPDIR}/mnt/fex"

# read available fex configurations
RADIOLIST=()
for FEX in ${FEXDIR}/*
do
	FEX=$(basename $FEX)
	if [ "$FEX" == "$BANANIAN_PLATFORM" ]; then {
	RADIOLIST+=("$FEX" "" "ON")
	} else {
	RADIOLIST+=("$FEX" "" "OFF")
	} fi
done

# show dialog
BANANIAN_PLATFORM=$(whiptail --title "Bananian hardware configuration" --radiolist \
	"\nPlease select your Banana board:" 20 78 10 \
	"${RADIOLIST[@]}" \
	3>&1 1>&2 2>&3)

# verify selection and set correct script.bin
if [[ -z $BANANIAN_PLATFORM ]]
then
	echo -e "\033[40;31m No platform selected. exiting!\033[0m"
else
	cp ${FEXDIR}/${BANANIAN_PLATFORM}/script.bin ${TMPDIR}/mnt/script.bin
	echo $BANANIAN_PLATFORM > /etc/bananian_platform
	echo -e "\033[32;40m Hardware configuration has been changed to: ${BANANIAN_PLATFORM}. Please reboot your system now!\033[0m"
fi

# clean up
umount ${TMPDIR}/mnt && rm -rf $TMPDIR
