#!/bin/bash
pmutemp() {
        # function to read out the thermal probe inside the AXP209 power
        # management unit via I2C
        CelsiusVal=$(awk '{printf ("%0.1f",$1/1000); }' </sys/devices/platform/sunxi-i2c.0/i2c-0/0-0034/temp1_input)
        case $1 in
                f|F)
                        echo ${CelsiusVal} | awk '{print "approx. "( ( 9/5 ) * $1 ) + 32"°F"}'
                        ;;
                *)
                        echo "approx. ${CelsiusVal}°C"
                        ;;
        esac
} # pmutemp

pmutemp $1
