#/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2016 Nico Isenbeck <contact@bananian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

KERNELMAJORVERSION=$(uname -r | grep -oE "[[:digit:]]{1}" | head -1)

echo -e -n "

---------------------------------------------------------------------------------
\033[40;37mYou are using Bananian $READABLE_VERSION\033[0m
\033[32;40mThis script will upgrade your installation to Bananian 16.04 r01\033[0m
---------------------------------------------------------------------------------

The following files will be modified:
-------------------------------------
boot partition:
/uImage

root filesystem:
/lib/modules/*
/lib/firmware/*
/usr/local/bin/bananian-config (del)
/usr/local/bin/bananian-hardware (del)
/usr/local/bin/bananian-update (del)
/usr/local/bin/bin2fex (del)
/usr/local/bin/fex2bin (del)
/usr/local/bin/fexc (del)
/usr/local/bin/pmutemp (del)
/usr/local/bin/raspi-config (del)
/usr/local/bin/soctemp (del)
/etc/apt/sources.list.d/bananian.list
/etc/kbd/config
/etc/rc.local
/etc/rsyslog.conf

Packages to be installed:
-------------------------
bananian-etc
bananian-tools
linux-image-3.4-bananian AND/OR
linux-image-4.4-bananian

Bananian packages to be upgraded:
---------------------------------
u-boot-bananian OR
u-boot-pro-bananian OR
u-boot-m2-bananian

Important changes:
--------------------
- 0000199: [Userland] Introduce bananian-settings to replace all entries in /etc/rc.local
- 0000198: [Hardware] bananian-hardware does not work on Linux 4.x
- 0000152: [Kernel] Switch between kernel 3.x and 4.x
- 0000124: [Userland] package bananian-update as a .deb file
- 0000012: [General] Kernel Update Script and other stuff as an apt repository
- 0000182: [Network] WIFI driver ap6210 not found under Kernel 4.3
- 0000194: [Kernel] Update Kernel 3.4.x
- 0000197: [Kernel] provide Linux 4.4.x packages
- 0000055: [Kernel] Division by zero in kernel. (3.4.90+)
- 0000183: [Hardware] update FAQ, pmutemp and soctemp related to Kernel 4.x
- 0000166: [General] Update U-Boot
- 0000176: [Kernel] Removing 4.2 kernel packages result in unbootable system
- 0000157: [Userland] rsyslog spams logs
- 0000184: [Kernel] HDMI output turns off on inactivity
- 0000175: [Kernel] Support for 8 channels hdmi
- 0000200: [Kernel] enable audio on Linux 4.x

For a list of all changes see our changelog:
https://dev.bananian.org/changelog_page.php?version_id=13

Incompatible changes:
--------------------
- All Bananian tools have been moved from /usr/local/bin to /usr/sbin. Adjust your scripts!

\033[0;31mDo you want to continue (yes/no)?\033[0m "
read start_upgrade

echo -e ""
if [ "$start_upgrade" != "yes" ]; then {
        echo -e "---------------------------------------------------------------------------------"
        echo -e "\033[40;31mupgrade canceled by user...\033[0m \n"
        rm -rf $TMPDIR
        exit
} fi

echo -e "---------------------------------------------------------------------------------"
echo -e "adding/updating Bananian repository... \n"
gpg --armor --export 24BFF712 | apt-key add -
echo "# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" > /etc/apt/sources.list.d/bananian.list
echo "# Use bananian-update to get the latest release!" >> /etc/apt/sources.list.d/bananian.list
echo "deb http://dl.bananian.org/packages/ 1604 main" >> /etc/apt/sources.list.d/bananian.list

echo -e "---------------------------------------------------------------------------------"
echo -e "updating package lists... (Get a coffee, this might take some time) \n"
aptitude update
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "installing bananian-etc... \n"
aptitude install -y bananian-etc
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "installing bananian-tools... \n"
aptitude install -y bananian-tools
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "installing kernel meta-package (linux-image, modules and firmware)... \n"
if [ $(dpkg-query -W -f='${Status}' linux-image-3.4\* 2>/dev/null | grep -c "ok installed") -eq 1 ]; then {
        aptitude install -y linux-image-3.4-bananian
} fi

if [ "$KERNELMAJORVERSION" -eq "4" ]; then {
	aptitude install -y linux-image-4.4-bananian
} fi
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "installing u-boot-bananian... \n"
UBOOTPACKAGE=$(dpkg -l | grep 'u-boot.*bananian' | awk -F ' ' '{print $2}')
if [ -n "$UBOOTPACKAGE" ]; then {
	aptitude install -y $UBOOTPACKAGE
} else {
	echo -e "\033[40;33mu-boot package not found. Skipping...\033[0m \n"
} fi
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "upgrading software... \n"
aptitude upgrade
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "deleting old files in /usr/local/bin... \n"
rm -f /usr/local/bin/bananian-config
rm -f /usr/local/bin/bananian-hardware
rm -f /usr/local/bin/bananian-update
rm -f /usr/local/bin/bin2fex
rm -f /usr/local/bin/fex2bin
rm -f /usr/local/bin/fexc
rm -f /usr/local/bin/pmutemp
rm -f /usr/local/bin/raspi-config
rm -f /usr/local/bin/soctemp
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "cleaning up /etc/rc.local... \n"
perl -i -0pe 's/\#\ generate\ new\ ssh\ host\ key\nif \[ \! -(s|f) \/etc\/ssh\/ssh_host_rsa_key(.|\n)*?\nfi( |)\n//' /etc/rc.local
perl -i -0pe 's/\#\ cpu\ frequency(.|\n)*?io_is_busy\n//' /etc/rc.local
perl -i -0pe 's/\#\ remount\ filesystem\ with\ noatime\ flag(.|\n)*?noatime\ \/\n//' /etc/rc.local
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "replacing /etc/rsyslog.conf... \n"
RSYSLOGCONF=$(sha256sum /etc/rsyslog.conf | awk -F ' ' '{print $1}')
if [ "$RSYSLOGCONF" = "93c6bde764222ed4359fcbf2c7ac7b44c914f06ae79c824219b7b70c5078e87c" ]; then {
	mv rsyslog.conf /etc/rsyslog.conf
} else {
	echo -e "\033[40;33munknown rsyslog.conf. Skipping...\033[0m \n"
} fi

echo -e "---------------------------------------------------------------------------------"
echo -e "adjusting screen blanking... \n"
sed -i "s/^BLANK_TIME=.*/BLANK_TIME=0/g" /etc/kbd/config
sed -i "s/^BLANK_DPMS=.*/BLANK_DPMS=off/g" /etc/kbd/config
sed -i "s/^POWERDOWN_TIME=.*/POWERDOWN_TIME=0/g" /etc/kbd/config
echo -e ""

echo -e "---------------------------------------------------------------------------------"
echo -e "\033[32;40mdone! please reboot your system now! (shutdown -r now)\033[0m \n"
